version: "3.8"

services:

  postgres-db:
    image: postgres:11-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=hlm_user
      - POSTGRES_PASSWORD=WeLQPIXacQoJ8owl
    networks:
      - healenium

  healenium:
    image: aliakseiashukha/hlm-backend-ai:0.1.4
    container_name: healenium
    restart: on-failure
    ports:
      - "7878:7878"
    links:
      - postgres-db
    environment:
      - SPRING_POSTGRES_DB=healenium
      - SPRING_POSTGRES_SCHEMA=healenium
      - SPRING_POSTGRES_USER=hlm_user
      - SPRING_POSTGRES_PASSWORD=WeLQPIXacQoJ8owl
      - SPRING_POSTGRES_DB_HOST=postgres-db
      - KEY_SELECTOR_URL=false
      - COLLECT_METRICS=true
      - HLM_LOG_LEVEL=info
    volumes:
      - ./screenshots/:/screenshots
      - ./logs/:/logs
    networks:
      - healenium

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.2
    container_name: selector-imitator
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - healenium

  hlm-proxy:
    image: aliakseiashukha/hlm-proxy-ai:0.1.5
    container_name: hlm-proxy
    restart: on-failure
    ports:
      - "8085:8085"
    environment:
      - RECOVERY_TRIES=1
      - SCORE_CAP=.6
      - HEAL_ENABLED=true
      - SELENIUM_SERVER_URL=http://selenium-hub:4444/wd/hub
      - APPIUM_SERVER_URL=http://host.docker.internal:4723/wd/hub
      - HEALENIUM_SERVER_URL=http://localhost:7878
      - HEALENIUM_SERVICE=http://healenium:7878
      - IMITATE_SERVICE=http://selector-imitator:8000
      - AI_NODE_SERVICE=http://host.docker.internal:3000
      - HLM_MANAGER_SERVICE=http://hlm-manager:9095
      - HLM_LOG_LEVEL=info
    volumes:
      - ./logs/:/logs
    networks:
      - healenium

  hlm-manager:
    image: aliakseiashukha/hlm-manager:0.1.5
    container_name: hlm-manager
    restart: on-failure
    ports:
      - "9095:9095"
    links:
      - postgres-db
    environment:
      - SPRING_POSTGRES_DB=healenium
      - SPRING_POSTGRES_SCHEMA=healenium
      - SPRING_POSTGRES_USER=hlm_user
      - SPRING_POSTGRES_PASSWORD=WeLQPIXacQoJ8owl
      - SPRING_POSTGRES_DB_HOST=postgres-db
      - HLM_BACKEND_SERVICE=http://healenium:7878
      - HLM_LOG_LEVEL=debug
    volumes:
      - ./logs/:/logs
    networks:
      - healenium

  node-chatgpt-api:
    image: aliakseiashukha/node-chatgpt-api:1.0.0
    container_name: node-chatgpt-api
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=c2stUEFoSDZyZnBlOHpsRUdTQWt4UFpUM0JsYmtGSmMyR0dQMEdhR3h5WkV1OEVYOXpo
    ports:
      - "3000:3000"
    networks:
      - healenium

  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=5
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=20
    networks:
      - healenium

  edge:
    image: selenium/node-edge:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - healenium

  firefox:
    image: selenium/node-firefox:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - healenium

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - healenium

networks:
  healenium:
    name: healenium
